export const INITIATE_FETCH = 'INITIATE_FETCH'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'

export const INITIATE_FETCH_ALL = 'INITIATE_FETCH_ALL'
export const FETCH_SUCCESS_ALL = 'FETCH_SUCCESS_ALL'
export const FETCH_FAILED_ALL = 'FETCH_FAILED_ALL'